# Generated by Django 2.2.16 on 2022-10-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221007_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='name',
            new_name='Name',
        ),
    ]
