# Generated by Django 2.2.16 on 2022-10-07 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20221007_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='Name',
            new_name='name',
        ),
    ]
