# Generated by Django 2.2.16 on 2022-10-07 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20221007_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
